### ISSUE TITLE
run "docker-compose -f docker-compose-simple.yaml up" failed

### ISSUE THREAD

**Issue by MagicVin** [kaiyuanshe/kcoin#113]
I just want to run the chaincode locally, but stopped on the first terminal when ran the "**docker-compose -f docker-compose-simple.yaml up**". 

```
peer         | 2019-02-20 15:17:57.175 UTC [gossip/election] propose -> DEBU 1b1 [243 207 228 28 171 240 246 50 47 126 76 107 39 195 188 89 124 172 71 55 154 250 154 119 204 184 74 34 122 52 159 71] : Entering
peer         | 2019-02-20 15:17:57.175 UTC [gossip/election] propose -> DEBU 1b2 [243 207 228 28 171 240 246 50 47 126 76 107 39 195 188 89 124 172 71 55 154 250 154 119 204 184 74 34 122 52 159 71] : Exiting
peer         | 2019-02-20 15:17:57.176 UTC [gossip/election] waitForInterrupt -> DEBU 1b3 [243 207 228 28 171 240 246 50 47 126 76 107 39 195 188 89 124 172 71 55 154 250 154 119 204 184 74 34 122 52 159 71] : Entering
peer         | 2019-02-20 15:17:59.074 UTC [gossip/discovery] periodicalSendAlive -> DEBU 1b4 Sleeping 5s
peer         | 2019-02-20 15:18:02.176 UTC [gossip/election] waitForInterrupt -> DEBU 1b5 [243 207 228 28 171 240 246 50 47 126 76 107 39 195 188 89 124 172 71 55 154 250 154 119 204 184 74 34 122 52 159 71] : Exiting
peer         | 2019-02-20 15:18:02.176 UTC [gossip/election] beLeader -> INFO 1b6 [243 207 228 28 171 240 246 50 47 126 76 107 39 195 188 89 124 172 71 55 154 250 154 119 204 184 74 34 122 52 159 71] : Becoming a leader
peer         | 2019-02-20 15:18:02.176 UTC [gossip/service] func1 -> INFO 1b7 Elected as a leader, starting delivery service for channel myc
peer         | 2019-02-20 15:18:02.177 UTC [deliveryClient] StartDeliverForChannel -> DEBU 1b8 This peer will pass blocks from orderer service to other peers for channel myc
peer         | 2019-02-20 15:18:02.178 UTC [gossip/election] leaderElection -> DEBU 1b9 [243 207 228 28 171 240 246 50 47 126 76 107 39 195 188 89 124 172 71 55 154 250 154 119 204 184 74 34 122 52 159 71] : Exiting
peer         | 2019-02-20 15:18:02.178 UTC [gossip/election] IsLeader -> DEBU 1ba [243 207 228 28 171 240 246 50 47 126 76 107 39 195 188 89 124 172 71 55 154 250 154 119 204 184 74 34 122 52 159 71] : Returning true
peer         | 2019-02-20 15:18:02.178 UTC [gossip/election] waitForInterrupt -> DEBU 1bb [243 207 228 28 171 240 246 50 47 126 76 107 39 195 188 89 124 172 71 55 154 250 154 119 204 184 74 34 122 52 159 71] : Entering

```
It worked well before but until met the code: "**peer | fatal error: unexpected signal during runtime execution**".

```
peer         | fatal error: unexpected signal during runtime execution
peer         | [signal SIGSEGV: segmentation violation code=0x1 addr=0x63 pc=0x7fe9b805a259]
peer         | 
peer         | runtime stack:
peer         | runtime.throw(0x111434c, 0x2a)
peer         | 	/opt/go/src/runtime/panic.go:616 +0x81
peer         | runtime.sigpanic()
peer         | 	/opt/go/src/runtime/signal_unix.go:372 +0x28e
peer         | 
peer         | goroutine 308 [syscall]:
peer         | runtime.cgocall(0xd23670, 0xc422230df8, 0x29)
peer         | 	/opt/go/src/runtime/cgocall.go:128 +0x64 fp=0xc422230db8 sp=0xc422230d80 pc=0x402134
peer         | net._C2func_getaddrinfo(0xc4222904b0, 0x0, 0xc4204b0a80, 0xc422a801b8, 0x0, 0x0, 0x0)
peer         | 	_cgo_gotypes.go:92 +0x55 fp=0xc422230df8 sp=0xc422230db8 pc=0x5f6bc5
peer         | net.cgoLookupIPCNAME.func1(0xc4222904b0, 0x0, 0xc4204b0a80, 0xc422a801b8, 0x8, 0x8, 0xc4204a3500)
peer         | 	/opt/go/src/net/cgo_unix.go:149 +0x13b fp=0xc422230e40 sp=0xc422230df8 pc=0x5fd92b
peer         | net.cgoLookupIPCNAME(0xc422291360, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
peer         | 	/opt/go/src/net/cgo_unix.go:149 +0x174 fp=0xc422230f38 sp=0xc422230e40 pc=0x5f8234
peer         | net.cgoIPLookup(0xc420508a20, 0xc422291360, 0x7)
peer         | 	/opt/go/src/net/cgo_unix.go:201 +0x4d fp=0xc422230fc8 sp=0xc422230f38 pc=0x5f88fd
peer         | runtime.goexit()
peer         | 	/opt/go/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc422230fd0 sp=0xc422230fc8 pc=0x45bb01
peer         | created by net.cgoLookupIP
peer         | 	/opt/go/src/net/cgo_unix.go:211 +0xaf
peer         | 
peer         | goroutine 1 [chan receive]:
peer         | github.com/hyperledger/fabric/peer/node.serve(0xc42038a450, 0x0, 0x3, 0x0, 0x0)
peer         | 	/opt/gopath/src/github.com/hyperledger/fabric/peer/node/start.go:363 +0x1802
peer         | github.com/hyperledger/fabric/peer/node.glob..func1(0x19a6c40, 0xc42038a450, 0x0, 0x3, 0x0, 0x0)
peer         | 	/opt/gopath/src/github.com/hyperledger/fabric/peer/node/start.go:112 +0x9c
peer         | github.com/hyperledger/fabric/vendor/github.com/spf13/cobra.(*Command).execute(0x19a6c40, 0xc42038a3f0, 0x3, 0x3, 0x19a6c40, 0xc42038a3f0)
peer         | 	/opt/gopath/src/github.com/hyperledger/fabric/vendor/github.com/spf13/cobra/command.go:698 +0x46d
peer         | github.com/hyperledger/fabric/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x19a72a0, 0x0, 0x19a65e0, 0x19a73e0)
peer         | 	/opt/gopath/src/github.com/hyperledger/fabric/vendor/github.com/spf13/cobra/command.go:783 +0x2e4
peer         | github.com/hyperledger/fabric/vendor/github.com/spf13/cobra.(*Command).Execute(0x19a72a0, 0xc42007ff30, 0x1)
peer         | 	/opt/gopath/src/github.com/hyperledger/fabric/vendor/github.com/spf13/cobra/command.go:736 +0x2b
peer         | main.main()
peer         | 	/opt/gopath/src/github.com/hyperledger/fabric/peer/main.go:52 +0x2e5
peer         | 
peer         | goroutine 18 [syscall]:
peer         | os/signal.signal_recv(0x0)
peer         | 	/opt/go/src/runtime/sigqueue.go:139 +0xa6
peer         | os/signal.loop()
peer         | 	/opt/go/src/os/signal/signal_unix.go:22 +0x22
peer         | created by os/signal.init.0
peer         | 	/opt/go/src/os/signal/signal_unix.go:28 +0x41

```

Then the terminal stopped outputting code, the latest outputted codes like below:

```
peer         | goroutine 30 [chan receive]:
peer         | github.com/hyperledger/fabric/core/chaincode/shim.(*inProcStream).Recv(0xc42224a770, 0x37e11d600, 0x0, 0xc4222377c8)
peer         | 	/opt/gopath/src/github.com/hyperledger/fabric/core/chaincode/shim/inprocstream.go:59 +0x45
peer         | github.com/hyperledger/fabric/core/chaincode/shim.chatWithPeer.func1()
peer         | 	/opt/gopath/src/github.com/hyperledger/fabric/core/chaincode/shim/chaincode.go:348 +0x3c
peer         | created by github.com/hyperledger/fabric/core/chaincode/shim.chatWithPeer
peer         | 	/opt/gopath/src/github.com/hyperledger/fabric/core/chaincode/shim/chaincode.go:377 +0x6f0
peer         | 
peer         | goroutine 33 [select]:
peer         | github.com/hyperledger/fabric/vendor/google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc422250740)
peer         | 	/opt/gopath/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/balancer_conn_wrappers.go:122 +0x14a
peer         | created by github.com/hyperledger/fabric/vendor/google.golang.org/grpc.newCCBalancerWrapper
peer         | 	/opt/gopath/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/balancer_conn_wrappers.go:113 +0x14f
peer         | 
peer         | goroutine 278 [chan receive]:
peer         | github.com/hyperledger/fabric/core/chaincode/shim.(*inProcStream).Recv(0xc420591b40, 0x0, 0xc4222862a0, 0xc323a9)
peer         | 	/opt/gopath/src/github.com/hyperledger/fabric/core/chaincode/shim/inprocstream.go:59 +0x45
peer         | github.com/hyperledger/fabric/core/chaincode/shim.chatWithPeer.func1()
peer         | 	/opt/gopath/src/github.com/hyperledger/fabric/core/chaincode/shim/chaincode.go:348 +0x3c
peer         | created by github.com/hyperledger/fabric/core/chaincode/shim.chatWithPeer
peer         | 	/opt/gopath/src/github.com/hyperledger/fabric/core/chaincode/shim/chaincode.go:377 +0x6f0
peer exited with code 2

```

Any suggestions are welcome!
Thanks!

**Comment by gsimon75** [comment]
Could you please add a note about how you managed to solve this?
I'm having a very similar segfault and most probably it would help a lot!
Thanks!
